[package]
name = "tpf3mp-server"
description = "The TPF3-MP dedicated server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
crc32fast.workspace = true
getrandom.workspace = true
postcard.workspace = true
quinn.workspace = true
ring.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-tungstenite.workspace = true
tpf3mp-net.workspace = true
tpf3mp-proto.workspace = true
tpf3mp-snapshot.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
tpf3mp-agent.workspace = true

[build-dependencies]
tpf3mp-buildinfo.workspace = true

[lints]
workspace = true
