#!/usr/bin/env python3
"""Builds the mod's gui/main/react.lua from the game's own file.

The game declares one layout-child builtin with the wrong helper
(docs/HOOKS.md, "The main menu's `WithComponentParams` banner"): at
`react.lua:658` it calls `DeclareBuiltinLayoutChildWithUserdata`, which is
for builtins the C++ side has already put in the table, and so looks up the
name it is about to declare, finds nil (the table starts that name at nil,
`react.lua:210`), and logs

    Missing builtin recipeId for (::/gui/main/react.lua:433 in
    DeclareBuiltinLayoutChildWithUserdata), name = WithComponentParams

`RegisterRecipeInner(nil, ...)` then registers the wrapper with no id, so
every layout that needed it is never drawn ("Preserved props ... of an
instance of WithComponentParams", and the game's "Entity does not create
view N"). It happens in every game, with or without this mod.

The fix is one line: a builtin the table does not have gets a fresh id,
made the way `RegisterRecipe` makes one (`api.gui.react.detail.makeRecipeId`,
`react.lua:410`). The builtins the C++ side does register keep the ids they
have, so nothing else changes.

The mod's copy is the game's file with that one line changed, served in
place of the game's through the same `resolveutil.loadfile` wrap that
serves `main_page.tl` (crates/tpf3mp-hook/src/menu_entry.rs,
`tools/lobby/make_main_page.py`). The game's file is in
`base/content/gui.zip` (`unzip gui.zip gui/main/react.lua`).

    python tools/lobby/make_react.py <the game's gui/main/react.lua>

The anchor must match exactly once, so a game patch that moves the line
fails loudly here rather than in the game.
"""
import argparse
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MOD = os.path.join(REPO, "mod", "tpf3mp_1")
OUT = os.path.join(MOD, "content", "gui", "main", "react.lua")

HEADER = '''-- TPF3-MP: the game's gui/main/react.lua with one line changed, served in
-- place of the game's file (docs/HOOKS.md, "The main menu's
-- `WithComponentParams` banner"). The game declares the `WithComponentParams`
-- layout child through `DeclareBuiltinLayoutChildWithUserdata`, which is for
-- the builtins the C++ side has already registered, so it looks the name up,
-- finds nil, logs "Missing builtin receipt/recipeId", and registers the
-- wrapper with no id: every layout that needed it is never drawn. This copy
-- gives a builtin the table has not got a fresh id instead, as
-- `RegisterRecipe` does. Every other builtin keeps the id it has.
--
-- Generated by tools/lobby/make_react.py; regenerate it when the game's file
-- changes. Every change is marked "TPF3-MP:".
'''

# The lookup `DeclareBuiltinLayoutChildWithUserdata` does, and what it becomes.
OLD = """local function DeclareBuiltinLayoutChildWithUserdata(name, fn)
	local recipeId = _react.builtin[name]
	if not recipeId then
		log.error("Missing builtin recipeId for", "name = " .. tostring(name))
	end"""
NEW = """local function DeclareBuiltinLayoutChildWithUserdata(name, fn)
	-- TPF3-MP: was `local recipeId = _react.builtin[name]`, which is nil for
	-- `WithComponentParams`: the game declares it here with a helper meant for
	-- the builtins the C++ side has already registered, so it looked up the
	-- name it was about to declare, logged "Missing builtin recipeId", and
	-- registered the wrapper with no id -- every layout that needed it was
	-- never drawn. A builtin the table has not got gets a fresh id, made as
	-- RegisterRecipe makes one (react.lua:410).
	local recipeId = _react.builtin[name] or api.gui.react.detail.makeRecipeId(name)
	if not recipeId then
		log.error("Missing builtin recipeId for", "name = " .. tostring(name))
	end"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("game", help="the game's gui/main/react.lua")
    args = parser.parse_args()

    with open(args.game, encoding="utf-8") as src:
        text = src.read()

    if text.count(OLD) != 1:
        print(f"anchor found {text.count(OLD)} times, expected once; "
              f"the game's file changed and this copy must be looked at", file=sys.stderr)
        return 1
    text = text.replace(OLD, NEW)
    # The game file's own relative paths stay: the hook serves it under the
    # game's path, so they resolve as they always did.
    text = HEADER + text

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as out:
        out.write(text)
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")

    content = os.path.join(MOD, "_content.json")
    listing = json.load(open(content, encoding="utf-8"))
    path = "gui/main/react.lua"
    if path not in listing["files"]:
        listing["files"].insert(0, path)
        print(f"listed {path} in _content.json")
        with open(content, "w", encoding="utf-8", newline="\n") as out:
            out.write(json.dumps(listing, indent=4) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())