-- Generated by `cargo run -p tpf3mp-bigmap -- --config <file> lua`; do not
-- edit. The added size rows, in the order the size dropdown shows them,
-- and the shape each ratio gives them, in tiles (x, y); false where the
-- settings cannot build that shape. peakMb: generation's expected peak
-- memory for the row's largest shape, in MB, the game's own included;
-- PROVISIONAL until Stage 0 measures it (the law is in
-- crates/tpf3mp-bigmap/src/memory_gate.rs).
return {
	{ label = "Big 32.8 km", tiles = 128, peakMb = 17285, shapes = { { 128, 128 }, { 180, 90 }, { 222, 74 }, { 250, 64 }, { 250, 58 } } },
	{ label = "Big 36.9 km", tiles = 144, peakMb = 20956, shapes = { { 144, 144 }, { 204, 102 }, { 250, 84 }, { 250, 72 }, { 250, 64 } } },
	{ label = "Big 41.0 km", tiles = 160, peakMb = 24963, shapes = { { 160, 160 }, { 228, 114 }, { 250, 92 }, { 250, 80 }, { 250, 72 } } },
	{ label = "Big 45.1 km", tiles = 176, peakMb = 28965, shapes = { { 176, 176 }, { 248, 124 }, { 250, 102 }, { 250, 88 }, { 250, 78 } } },
}
