-- Generated by `cargo run -p tpf3mp-bigmap -- --config <file> lua`; do not
-- edit. The added size rows, in the order the size dropdown shows them,
-- and the shape each ratio gives them, in tiles (x, y); false where the
-- settings cannot build that shape. peakMb: generation's expected peak
-- memory for the row's largest shape, in MB, the game's own included;
-- measured by Stage 0 at stock Gigantomaniac, one temperate run per
-- shape, and extrapolated to these sizes (the law is in
-- crates/tpf3mp-bigmap/src/memory_gate.rs). densityScale: the scale on
-- the stock Medium town and industry density that gives the row's
-- square stock Gigantomaniac 1:1's counts.
return {
	{ label = "Big 32.8 km", tiles = 128, peakMb = 16836, densityScale = 0.7656, shapes = { { 128, 128 }, { 180, 90 }, { 222, 74 }, { 250, 64 }, { 250, 58 }, false, false, false, false, false } },
	{ label = "Big 36.9 km", tiles = 144, peakMb = 19907, densityScale = 0.6049, shapes = { { 144, 144 }, { 204, 102 }, { 250, 84 }, { 250, 72 }, { 250, 64 }, false, false, false, false, false } },
	{ label = "Big 41.0 km", tiles = 160, peakMb = 23260, densityScale = 0.4900, shapes = { { 160, 160 }, { 228, 114 }, { 250, 92 }, { 250, 80 }, { 250, 72 }, false, false, false, false, false } },
	{ label = "Big 45.1 km", tiles = 176, peakMb = 26608, densityScale = 0.4050, shapes = { { 176, 176 }, { 248, 124 }, { 250, 102 }, { 250, 88 }, { 250, 78 }, false, false, false, false, false } },
	stock = {
		[16] = { peakMb = 6042, shapes = { { 36, 6 }, { 42, 6 }, { 48, 6 }, { 54, 6 }, { 60, 6 } } },
		[32] = { peakMb = 6590, shapes = { { 84, 14 }, { 84, 12 }, { 96, 12 }, { 90, 10 }, { 100, 10 } } },
		[44] = { peakMb = 7176, shapes = { { 108, 18 }, { 112, 16 }, { 128, 16 }, { 126, 14 }, { 140, 14 } } },
		[56] = { peakMb = 8076, shapes = { { 132, 22 }, { 154, 22 }, { 160, 20 }, { 162, 18 }, { 180, 18 } } },
		[64] = { peakMb = 8727, shapes = { { 156, 26 }, { 168, 24 }, { 176, 22 }, { 198, 22 }, { 200, 20 } } },
		[80] = { peakMb = 10032, shapes = { { 192, 32 }, { 210, 30 }, { 224, 28 }, { 234, 26 }, false } },
		[96] = { peakMb = 12249, shapes = { { 240, 40 }, false, false, false, false } },
		[112] = { peakMb = 0, shapes = { false, false, false, false, false } },
	},
}
