//! The ladder as the mod's data file,
//! `mod/tpf3mp_bigmap_1/content/scripts/tpf3mp_bigmap/ladder.lua`.
//!
//! The mod holds the menu's side of big maps: TF3's New Game page is a
//! script, and the mod's copy of it (served by the hook, [`crate::page`])
//! adds the size rows itself. It reads the rows from this file, generated
//! from the settings by `cargo run -p tpf3mp-bigmap -- --config <file> lua`,
//! so the menu offers exactly the sizes the checks here allow. Each row
//! keeps one entry per ratio, in the dropdown's order; a shape the settings
//! cannot build is `false`, never left out, so a ratio's position always
//! names its shape. `peakMb` is generation's expected peak for the row's
//! largest buildable shape, the game's own use included, which the page
//! holds against the machine's memory. `densityScale` is the scale on the
//! stock Medium town and industry density that gives the row's square the
//! counts stock Gigantomaniac 1:1 gets at Medium: counts are a density per
//! km², so it is the area ratio, `(stock max tiles / row tiles)²`. The page
//! offers one density level per row in the ladder (every row, offered or
//! not, so a level means the same on every machine).

use crate::ceilings::check;
use crate::config::Config;
use crate::ladder::shapes;
use crate::world::WorldModel;

/// The mod's data file for `config`, on `world`. Rows none of whose shapes
/// can be built are left out.
pub fn lua(world: &WorldModel, config: &Config) -> String {
    let mut out = String::from(
        "-- Generated by `cargo run -p tpf3mp-bigmap -- --config <file> lua`; do not\n\
         -- edit. The added size rows, in the order the size dropdown shows them,\n\
         -- and the shape each ratio gives them, in tiles (x, y); false where the\n\
         -- settings cannot build that shape. peakMb: generation's expected peak\n\
         -- memory for the row's largest shape, in MB, the game's own included;\n\
         -- measured by Stage 0 at stock Gigantomaniac, one temperate run per\n\
         -- shape, and extrapolated to these sizes (the law is in\n\
         -- crates/tpf3mp-bigmap/src/memory_gate.rs). densityScale: the scale on\n\
         -- the stock Medium town and industry density that gives the row's\n\
         -- square stock Gigantomaniac 1:1's counts.\n\
         return {\n",
    );
    for row in config.rows(world) {
        let reports: Vec<_> = shapes(&row, config.sizes.max_tiles)
            .into_iter()
            .map(|(x, y)| check(world, config, x, y))
            .collect();
        let built: Vec<Option<(u32, u32)>> = reports
            .iter()
            .map(|report| report.buildable().then_some(report.tiles))
            .collect();
        if built.iter().all(Option::is_none) {
            continue;
        }
        let peak_mb = reports
            .iter()
            .filter(|report| report.buildable())
            .map(|report| report.peak_mb)
            .fold(0.0, f64::max)
            .ceil();
        let cells: Vec<String> = built
            .into_iter()
            .map(|shape| match shape {
                Some((x, y)) => format!("{{ {x}, {y} }}"),
                None => "false".to_owned(),
            })
            .collect();
        let stock_tiles = f64::from(world.stock_max_tiles.value);
        let density_scale = (stock_tiles / f64::from(row.tiles)).powi(2);
        out.push_str(&format!(
            "\t{{ label = {:?}, tiles = {}, peakMb = {peak_mb}, densityScale = {density_scale:.4}, shapes = {{ {} }} }},\n",
            row.label,
            row.tiles,
            cells.join(", ")
        ));
    }
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_data_holds_only_buildable_sizes() {
        let world = WorldModel::TPF2_BUILD_35924;
        // Stock settings: nothing past the street raster's 180-tile wall.
        let stock = lua(&world, &Config::default());
        assert!(stock.contains("\"32 x 32 km\""));
        assert!(!stock.contains("\"56 x 56 km\""), "{stock}");
        let (big, _) =
            Config::from_toml("[limits]\nstreet_raster = true\noctree_depth = 11").unwrap();
        let big = lua(&world, &big);
        assert!(big.contains("\"128 x 128 km\""), "{big}");
    }

    #[test]
    fn a_shape_that_cannot_be_built_keeps_its_place() {
        // 40 km at 1:3 is 276 x 92 tiles: 70.7 km long, past the stock
        // root's 65.5 km; 1:4 and 1:5 are longer still.
        let stock = lua(&WorldModel::TPF2_BUILD_35924, &Config::default());
        let row = stock
            .lines()
            .find(|line| line.contains("\"40 x 40 km\""))
            .unwrap();
        assert!(
            row.ends_with("{ 160, 160 }, { 228, 114 }, false, false, false } },"),
            "{row}"
        );
    }

    #[test]
    fn the_peak_is_the_largest_buildable_shape() {
        // 32 km on TPF2: 1:3 is 222 x 74 tiles, 16,428 tiles against the
        // square's 16,384, so 1,076.6 km² is the largest buildable shape
        // (1:5's 290 tiles is past the root); 2.5 MB per km² plus the
        // game's 4,096 MB.
        let stock = lua(&WorldModel::TPF2_BUILD_35924, &Config::default());
        let row = stock
            .lines()
            .find(|line| line.contains("\"32 x 32 km\""))
            .unwrap();
        assert!(row.contains("peakMb = 6788,"), "{row}");
    }

    #[test]
    fn the_density_scale_keeps_the_largest_stock_maps_counts() {
        // TF3: Gigantomaniac 1:1 is 112 x 112 tiles; a 176-tile square is
        // (112 / 176)² = 0.405 of the density for the same counts.
        let (big, _) = Config::from_toml(
            "[sizes]
add_rows = true
rows = [{ label = \"Big 45.1 km\", tiles = 176 }]",
        )
        .unwrap();
        let lua = lua(&WorldModel::TF3_BUILD_40408, &big);
        assert!(lua.contains("densityScale = 0.4050,"), "{lua}");
    }
}
