//! The ladder as the mod's data file,
//! `mod/tpf3mp_bigmap_1/content/scripts/tpf3mp_bigmap/ladder.lua`.
//!
//! The mod holds the menu's side of big maps: on TF3 the New Game menu may
//! be a script recipe, where a mod can add the size rows itself. It reads
//! the rows from this file, generated from the settings by
//! `cargo run -p tpf3mp-bigmap -- --config <file> lua`, so the menu offers
//! exactly the sizes the checks here allow. Each row keeps one entry per
//! ratio, in the dropdown's order; a shape the settings cannot build is
//! `false`, never left out, so a ratio's position always names its shape.

use crate::ceilings::check;
use crate::config::Config;
use crate::ladder::shapes;
use crate::world::WorldModel;

/// The mod's data file for `config`, on `world`. Rows none of whose shapes
/// can be built are left out.
pub fn lua(world: &WorldModel, config: &Config) -> String {
    let mut out = String::from(
        "-- Generated by `cargo run -p tpf3mp-bigmap -- --config <file> lua`; do not\n\
         -- edit. The added size rows, in the order the size dropdown shows them,\n\
         -- and the shape each ratio gives them, in tiles (x, y); false where the\n\
         -- settings cannot build that shape.\n\
         return {\n",
    );
    for row in config.rows(world) {
        let built: Vec<Option<(u32, u32)>> = shapes(&row, config.sizes.max_tiles)
            .into_iter()
            .map(|(x, y)| check(world, config, x, y).buildable().then_some((x, y)))
            .collect();
        if built.iter().all(Option::is_none) {
            continue;
        }
        let cells: Vec<String> = built
            .into_iter()
            .map(|shape| match shape {
                Some((x, y)) => format!("{{ {x}, {y} }}"),
                None => "false".to_owned(),
            })
            .collect();
        out.push_str(&format!(
            "\t{{ label = {:?}, tiles = {}, shapes = {{ {} }} }},\n",
            row.label,
            row.tiles,
            cells.join(", ")
        ));
    }
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_data_holds_only_buildable_sizes() {
        let world = WorldModel::TPF2_BUILD_35924;
        // Stock settings: nothing past the street raster's 180-tile wall.
        let stock = lua(&world, &Config::default());
        assert!(stock.contains("\"32 x 32 km\""));
        assert!(!stock.contains("\"56 x 56 km\""), "{stock}");
        let (big, _) =
            Config::from_toml("[limits]\nstreet_raster = true\noctree_depth = 11").unwrap();
        let big = lua(&world, &big);
        assert!(big.contains("\"128 x 128 km\""), "{big}");
    }

    #[test]
    fn a_shape_that_cannot_be_built_keeps_its_place() {
        // 40 km at 1:3 is 276 x 92 tiles: 70.7 km long, past the stock
        // root's 65.5 km; 1:4 and 1:5 are longer still.
        let stock = lua(&WorldModel::TPF2_BUILD_35924, &Config::default());
        let row = stock
            .lines()
            .find(|line| line.contains("\"40 x 40 km\""))
            .unwrap();
        assert!(
            row.ends_with("{ 160, 160 }, { 228, 114 }, false, false, false } },"),
            "{row}"
        );
    }
}
