[package]
name = "tpf3mp-proto"
description = "Wire protocol shared by the TPF3-MP server and agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
base64.workspace = true
postcard.workspace = true
ring.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
