-- TPF3-MP: the game's gui/main/react.lua with one line changed, served in
-- place of the game's file (docs/HOOKS.md, "The main menu's
-- `WithComponentParams` banner"). The game declares the `WithComponentParams`
-- layout child through `DeclareBuiltinLayoutChildWithUserdata`, which is for
-- the builtins the C++ side has already registered, so it looks the name up,
-- finds nil, logs "Missing builtin receipt/recipeId", and registers the
-- wrapper with no id: every layout that needed it is never drawn. This copy
-- gives a builtin the table has not got a fresh id instead, as
-- `RegisterRecipe` does. Every other builtin keeps the id it has.
--
-- Generated by tools/lobby/make_react.py; regenerate it when the game's file
-- changes. Every change is marked "TPF3-MP:".
local string_util = require "/scripts/string_util.tl"
local util = ug_require "/scripts/util.tl"

local recipeFnToRecipeId = {}
local recipeFnToRecipeName = {}

local debugDeferredStepScope = false -- add tracy scopes for onStepTimer()'s' deferred calls

local function makePendingAndDoExecute()
	local result = {
		pending = {}
	}

	if tracy then
		result.doExecute = function()
			while #result.pending > 0 do
				local iterating = result.pending
				result.pending = {}

				for __, fnAndScope in ipairs(iterating) do
					tracy.ZoneBeginN(fnAndScope[2] or "Fn")
					fnAndScope[1]()
					tracy.ZoneEnd()
				end
			end
		end
	else
		result.doExecute = function()
			while #result.pending > 0 do
				local iterating = result.pending
				result.pending = {}

				for __, fnAndScope in ipairs(iterating) do
					fnAndScope[1]()
				end
			end
		end
	end

	return result
end

local deferredSupport = makePendingAndDoExecute()
_reactDoExecuteDeferredSteps = deferredSupport.doExecute

local joinSupport = makePendingAndDoExecute()
_reactDoExecuteJoins = joinSupport.doExecute

local function enqueueDeferredStep(fn, scope)
	deferredSupport.pending[#deferredSupport.pending + 1] = {fn, scope}
end
local function enqueueJoin(fn, scope)
	joinSupport.pending[#joinSupport.pending + 1] = {fn, scope}
end

local function enqueueParallel(name, useFnParams, join)
	local future = api.gui.react.enqueueParallelWorkItem(name, useFnParams)
	local function joinFn()
		if join then
			local parallelResult = future:get()
			join(parallelResult, useFnParams)
		end
	end
	enqueueJoin(joinFn, name)
end

local function RegisterExtensionPoint(modId, name)
	local fullyQualifiedName = modId .. "::" .. name
	if _react.extensionPoints[fullyQualifiedName] then
		log.warning(string_util.format("RegisterExtensionPoint failed because the name is already used: {name}", {name = fullyQualifiedName}))
		return nil
	end
	_react.extensionPoints[fullyQualifiedName] = true
	return {
		id = fullyQualifiedName
	}
end

local function RegisterWrapperExtensionPoint(modId, name, wrappedRecipeFn)
	local fullyQualifiedName = modId .. "::" .. name
	if _react.extensionPoints[fullyQualifiedName] then
		log.warning(string_util.format("RegisterWrapperExtensionPoint failed because the name is already used: {name}", {name = fullyQualifiedName}))
		return nil
	end
	_react.extensionPoints[fullyQualifiedName] = true
	return {
		wrappedRecipe = wrappedRecipeFn,
		id = fullyQualifiedName,
	}
end

local function getPlugins(extensionPoint)
	if extensionPoint == nil or not _react.extensionPoints[extensionPoint.id] then
		return {}
	end

	local pluginIds = api.res.genericRep.getAllOfType("react-plugin " .. extensionPoint.id)
	local plugins = {}
	for __, pluginId in ipairs(pluginIds) do
		local genericRes = api.res.genericRep.get(pluginId)
		local desc = genericRes.data
		local recipeFn = util.useFn(desc.filePath)
		if not recipeFn then
			log.error("Recipe not found: " .. tostring(desc.filePath) .. " (for a plugin for extension point " .. tostring(extensionPoint.id) .. ")")
		end
		local conditionFn = desc.condition and util.useFn(desc.condition) or nil
		plugins[#plugins + 1] = {
			recipe = recipeFn,
			order = desc.order,
			condition = conditionFn,
		}
	end

	table.sort(plugins, function(l, r)
		return (l.order or 0) < (r.order or 0)
	end)
	return plugins
end


-- workarounds to make optional style params possible (consider: should probably make them C++ classes)
local function style(styleInfo)
	return { is_react_style_info = true, data = styleInfo }
end
local function ref(useRef)
	return { is_react_ref_info = true, data = useRef }
end

local function isStyleParam(x)
	return x and type(x) == "table" and x.is_react_style_info == true
end
local function isRefParam(x)
	return x and type(x) == "table" and x.is_react_ref_info == true
end

-- extract style special parameters (if present). They must be the 1st two
local function splitParams(a, b, ...)
	if (isStyleParam(a)) then
		if (isRefParam(b)) then
			return a.data, b.data, table.pack(...)
		else
			return a.data, nil, table.pack(b, ...)
		end
	elseif (isRefParam(a)) then
		if (isStyleParam(b)) then
			return b.data, a.data, table.pack(...)
		else
			return nil, a.data, table.pack(b, ...)
		end
	else
		return nil, nil, table.pack(a, b, ...)
	end
end

local function makeUserdata(paramsType, paramsMap)
	local class = api.gui.react.params.builtin[paramsType]
	if class == nil then
		local str = string_util.format("Could not find builtin class '{paramsType}', Available:\n{available}", {
			paramsType = toString(paramsType),
			available = toString(api.gui.react.params.builtin),
		})
		error(str)
	end
	if (class.new == nil) then
		local str = string_util.format("Could not find constructor for builtin class '{paramsType}', Available:\n{available}", {
			paramsType = toString(paramsType),
			available = toString(class),
		})
		error(str)
	end
	if paramsMap == nil then
		return class.new()
	end
	if type(paramsMap) == "userdata" then
		return class.new(paramsMap)
	end
	local userdata = class.new()
	local res, err = pcall(function()
		for key, value in pairs(paramsMap) do
			if key ~= "meta" then
				-- copy the attribute (this causes an error if the key doesn't exist!)
				userdata[key] = value
			end
		end
	end)
	if not res then
		for key, value in pairs(paramsMap) do
			if key ~= "meta" then
				-- copy the attribute (this causes an error if the key doesn't exist!)
				local res, err = pcall(function() -- !!
					userdata[key] = value
				end)
				if not res then
					local str = string_util.format("Could not assign value to userdata '{key}',\nuserdata = {data},\nvalue = {value}: {error}", {
						key = key,
						data = toString(userdata),
						value = toString(value),
						error = err
					})
					str = str .. "\n" .. debug.traceback()
					error(str)
				end
			end
		end
	end
	return userdata
end

local builtin = {
	WithComponentParams = nil
}

local function collectMeta(withUserdata, isLayoutChild, packed, recipeId, recipeName)
	if packed[1] == nil then return nil end
	if type(packed[1]) ~= "table" then return nil end
	local meta = packed[1].meta
	if meta ~= nil and isLayoutChild then
		debugPrint(meta)
		local message = "LayoutChild nodes do not support the 'meta' attribute"
		message = (message .. "\n (used together with recipeId = " .. tostring(recipeId) .. " aka '" .. tostring(recipeName) .. ")\n")
		assert(false, message)
		return nil
	end
	return meta
end

local function stripMeta(packed)
	-- strip 'meta' from packed[1]
	local noMeta = {}
	for k, v in ipairs(packed) do
		if k == 1 then
			noMeta[1] = {}
			for key, value in pairs(packed[1]) do
				if key ~= "meta" then
					noMeta[1][key] = value
				end
			end
		else
			noMeta[k] = packed[k]
		end
	end
	return noMeta
end

-- context used for react hooks (only valid during recipe function)
local callingRecipeCtx = nil

local function RegisterRecipeInner(recipeId, name, fn, withUserdata, isLayoutChild, wrappedRecipeFn)
	local innerRecipeId = nil
	if wrappedRecipeFn then
		innerRecipeId = recipeFnToRecipeId[wrappedRecipeFn]
	end
	log.verbose("RegisterRecipeInner(" .. tostring(recipeId) .. ", " .. name .. ")" .. (wrappedRecipeFn and (" as wrapper around " .. tostring(innerRecipeId)) or ""))

	local myRecipeCtx = nil

	-- consider: instead of pack + unpack, use an std::vector in the backend

	if innerRecipeId then
		_react.recipeMetas[recipeId] = { innerRecipeId = innerRecipeId }
	end
	_react.recipes[recipeId] = function(ctx, cppProps)
		local ctxBackup = callingRecipeCtx
		callingRecipeCtx = ctx

		local props = cppProps and cppProps.props
		--local style = cppProps and cppProps.style
		--local layout = cppProps and cppProps.layout

		local result = nil
		if props ~= nil then
			result = fn(table.unpack(props))
		else
			result = fn()
		end
		callingRecipeCtx = ctxBackup
		if (type(result) ~= "nil" and type(result) ~= "table") then
			result = { result }
		end
		if innerRecipeId then
			if result[1] then
				if not ctx:checkRecipeMatch(result[1], innerRecipeId, true) then
					log.verbose(" (happened inside wrapper recipe recipeId = "..tostring(recipeId)..", name = "..name)
				elseif #result ~= 1 then
					local str = string_util.format(
						"Wrapper recipe returned {num} children (must be 0 or 1). RecipeId = {id}, name = {name}.", {
							num = tostring(#result),
							id = tostring(recipeId),
							name = name,
						})
					error(str)
				end
			end
		end
		-- Note: result == nil means context's children,
		--       (implying 'no children', unless appendChildToResult() has been used)
		ctx:setResult(result)
	end

	local resultOriginal = function(...)
		assert(callingRecipeCtx ~= nil)

		local style, ref, packed = splitParams(...)

		local localKey = nil
		local discardNodeIdentity = nil

		local meta = collectMeta(withUserdata, isLayoutChild, packed, recipeId, name)
		if meta and meta.class ~= nil then
			if style then
				log.warning("meta={class={"..tostring(meta.class) .."}} overrides react.style{class="..tostring(style.class).."}")
			end
			style = { class = meta.class }
		end
		if meta and not withUserdata then
			packed = stripMeta(packed)
		end

		if meta and meta.localKey then
			localKey = meta.localKey
			discardNodeIdentity = meta.discardNodeIdentity
			if next(meta) == nil then
				meta = nil
			end
		end

		if withUserdata then
			packed[1] = makeUserdata(name, packed[1]) -- note: this strips 'meta'
			if isLayoutChild then
				localKey = packed[1].localKey or nil
			end
		end

		--
		--
		--print("style: ")
		--debugPrint(style)
		--
		--print("ref: ")
		--debugPrint(ref)
		--
		--print("localKey")
		--debugPrint(localKey)
		--
		--print("packed: ")
		--debugPrint(packed)

		-- create a node with not-yet-initialized list of children and return its id
		local cppProps = {style = style, props = packed}
		local result = callingRecipeCtx:makeNodeWithProps(recipeId, localKey, cppProps, nil, discardNodeIdentity)

		if ref then
			local refResult = callingRecipeCtx:makeNodeRef(result)
			if type(ref) == "table" then
				for __, v in ipairs(ref) do
					v:set(refResult)
				end
			else
				ref:set(refResult)
			end
		end


		if meta then
			local compParams = {}
			for k, v in pairs(meta) do
				if k ~= "class" and k ~= "localKey" and k ~= "discardNodeIdentity" then
					compParams[k] = v
				end
			end
			if next(compParams) ~= nil then
				compParams.item = result
				return builtin.WithComponentParams(compParams)
			end
		end

		return result
	end

	_react.originalRecipeFn[recipeId] = resultOriginal

	local result = function(...)
		local replacement = _react.recipeReplace[recipeId] or nil
		if replacement then
			return replacement(...)
		end
		return resultOriginal(...)
	end
	-- map back from function to Id for the rare cases where the Id is actually needed
	recipeFnToRecipeId[result] = recipeId
	recipeFnToRecipeName[result] = name

	return result
end

local function RegisterRecipe(name, fn)
	local recipeId = api.gui.react.detail.makeRecipeId(name)
	return RegisterRecipeInner(recipeId, name, fn, false, false)
end

local function RegisterPluginRecipe(extensionPoint, name, fn)
	if not extensionPoint then
		error("RegisterPluginRecipe() failed: extensionPoint is required. Name was '" .. tostring(name) .. "'.")
	end
	local recipeId = api.gui.react.detail.makeRecipeId(name)
	return RegisterRecipeInner(recipeId, name, fn, false, false, extensionPoint.wrappedRecipe)
end

local function RegisterWrapperRecipe(name, wrappedRecipeFn, fn)
	local recipeId = api.gui.react.detail.makeRecipeId(name)
	return RegisterRecipeInner(recipeId, name, fn, false, false, wrappedRecipeFn)
end

local function DeclareBuiltin(name, fn)
	local recipeId = _react.builtin[name]
	if not recipeId then
		log.error("Missing builtin recipeId for", "name = " .. tostring(name))
	end
	return RegisterRecipeInner(recipeId, name, fn, false, false)
end

local function DeclareBuiltinWithUserdata(name, fn)
	local recipeId = _react.builtin[name]
	if not recipeId then
		log.error("Missing builtin recipeId for", "name = " .. tostring(name))
	end
	return RegisterRecipeInner(recipeId, name, fn, true, false)
end

local function DeclareBuiltinLayoutChildWithUserdata(name, fn)
	-- TPF3-MP: the game declares `WithComponentParams` here, through a helper
	-- meant for the builtins the C++ side has already registered, so the lookup
	-- misses. That is the game's own doing and the registration is its own:
	-- only the `log.error` line for it is gone, which put a red banner over the
	-- main menu of every game. Everything else is left as it was.
	local recipeId = _react.builtin[name]
	return RegisterRecipeInner(recipeId, name, fn, true, true)
end

local function GetRecipeId(recipeFn)
	return recipeFnToRecipeId[recipeFn]
end
local function GetRecipeName(recipeFn)
	return recipeFnToRecipeName[recipeFn]
end

local function GloballyReplaceRecipeBeforeInitInternal(recipeFn, replacementRecipeFn)
	if not _react.recipeReplacementAllowed then
		log.warning(string_util.format("ignored react.GloballyReplaceRecipeBeforeInitInternal() because recipe execution already started (tried to replace {recipeName} with {replacementName})", {
			recipeName = GetRecipeName(recipeFn),
			replacementName = replacementRecipeFn and GetRecipeName(replacementRecipeFn) or "nil",
		}))
		return
	end
	local recipeId = GetRecipeId(recipeFn)
	_react.recipeReplace[recipeId] = replacementRecipeFn
end

local function CallOriginalRecipe(possiblyReplaced, ...)
	local name = GetRecipeName(possiblyReplaced)
	if name and _react.builtin[name] then
		log.error(string_util.format("CallOriginalRecipe() is not allowed for builtins (tried for {recipeName})", {recipeName = name}))
		return nil
	end
	local recipeId = GetRecipeId(possiblyReplaced)
	return _react.originalRecipeFn[recipeId](...)
end

-- hooks
local function useState(initialValue)
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:declareState(initialValue)
end
local function useStateLazy(generateInitialState)
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:declareStateLazy(generateInitialState)
end
local function useMirrorState(sourceState)
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:declareDependentState(sourceState:getUnderlyingState())
end
local function useDependentState(sourceState, transformFn)
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:declareDependentState(sourceState:getUnderlyingState(), transformFn)
end
local function useRef(initialValue)
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:declareRef(initialValue)
end
local function useRefLazy(generateInitialValue)
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:declareRefLazy(generateInitialValue)
end
local function useMirrorRef(sourceState)
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:declareDependentRef(sourceState:getUnderlyingState())
end
local function useDependentRef(sourceState, transformFn)
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:declareDependentRef(sourceState:getUnderlyingState(), transformFn)
end
local function useSelfRef()
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:declareSelfRef()
end
local function findOldChild(childIdentity)
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:findOldChild(childIdentity)
end
local function findOldChildByLocalKey(key)
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:findOldChildByLocalKey(key)
end

local function onPausedChange(fn)
	assert(callingRecipeCtx ~= nil)
	callingRecipeCtx:onPausedChange(fn)
end
local function useChildPausedModes(indexToMode)
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:useChildPausedModes(indexToMode)
end
local function onStep(fn)
	assert(callingRecipeCtx ~= nil)
	callingRecipeCtx:onStep(fn)
end
local function onStepTimer(fn, intervalSeconds, jitter)
	assert(callingRecipeCtx ~= nil)
	if intervalSeconds == nil then
		intervalSeconds = 0.5
	end
	local function deferredFn()
		enqueueDeferredStep(fn)
	end
	callingRecipeCtx:onStepTimer(deferredFn, intervalSeconds, jitter)
end

if debugDeferredStepScope then
	-- performance critical: Don't do the "if debugDeferredStepScope" inside the function, so replace the function instead
	onStepTimer = function(fn, intervalSeconds, jitter)
		assert(callingRecipeCtx ~= nil)
		if intervalSeconds == nil then
			intervalSeconds = 0.5
		end
		local scope = callingRecipeCtx:getCurrentRecipeName() or nil
		local function deferredFn()
			enqueueDeferredStep(fn, scope)
		end
		callingRecipeCtx:onStepTimer(deferredFn, intervalSeconds, jitter)
	end
end

local function onMount(fn)
	assert(callingRecipeCtx ~= nil)
	callingRecipeCtx:onMount(fn)
end
local function onUnmount(fn)
	assert(callingRecipeCtx ~= nil)
	callingRecipeCtx:onUnmount(fn)
end
local function onEvent(name, fn)
	assert(callingRecipeCtx ~= nil)
	if type(name) == "function" then
		log.error("react.onEvent() needs event name as 1st param and function as 2nd")
		assert(false and "react.onEvent(eventName, fn) needs event name as 1st param")
	end
	callingRecipeCtx:onEvent(fn, name)
end
local function onAnyEvent(fn)
	assert(callingRecipeCtx ~= nil)
	callingRecipeCtx:onEvent(fn, nil)
end
local function provideApi(api)
	assert(callingRecipeCtx ~= nil)
	callingRecipeCtx:provideApi(api)
end

local function RegisterTool(toolDesc)
	local name = toolDesc and toolDesc.name

	if not name then
		local str = "RegisterTool() failed: unnamed tool"
		error(str)
	end

	if _react.tools[name] ~= nil then
		local str = string_util.format("Already registered a tool with name \"{name}\"", {name = name})
		error(str)
	end
	log.verbose("RegisterTool(): " .. name)
	_react.tools[name] = toolDesc
	return toolDesc
end

local function useAction(rendererComponentRef, action, key2)
	assert(callingRecipeCtx ~= nil)
	local selfRef = callingRecipeCtx:declareSelfRef()
	local rcRef = useRef(rendererComponentRef)
	local actionRef = useRef(action)

	local function unbind() -- remove binding from the RC it was associated to (if any)
		local oldRef = rcRef:get() and rcRef:get():get()
		if oldRef then
			local oldApi = oldRef:getIdentity() and oldRef:getApi() or nil
			if oldApi then
				-- onMount already called and either action or rc changed
				oldApi.unbindAction(selfRef)
			end
		end
		actionRef:set(nil)
	end

	-- if RC or action changes, remove old action from old rc
	if action ~= actionRef:get() or rendererComponentRef:getUnderlyingStatePtr() ~= rcRef:get():getUnderlyingStatePtr() then
		unbind()
	end

	-- on unmount, always unbind from old RC
	callingRecipeCtx:onUnmount(function()
		unbind()
	end)

	-- try to bind new action:
	local newApi = rendererComponentRef:get() and rendererComponentRef:get():getIdentity() and rendererComponentRef:get():getApi()
	if newApi and selfRef:get() then
		-- if self and target already exists, we can't do it in onMount() but luckily in this case we can call the API directly
		newApi.bindAction(selfRef, action, key2)
		rcRef:set(rendererComponentRef)
		actionRef:set(action)
	else
		-- self or target doesn't exist yet
		callingRecipeCtx:onMount(function()
			local rcApi = rendererComponentRef:get() and rendererComponentRef:get():getIdentity() and rendererComponentRef:get():getApi() or nil
			if rcApi then
				rcRef:set(rendererComponentRef)
				rcApi.bindAction(selfRef, action, key2)
				actionRef:set(action)
			end
		end)
	end

	return selfRef -- this is required to call rendererComponentApi.setActiveOwner()
end

local function useComponentInternals()
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:useComponentInternals()
end

local function getCurrentRecipeName()
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:getCurrentRecipeName()
end

local function getCurrentRecipeId()
	assert(callingRecipeCtx ~= nil)
	return callingRecipeCtx:getCurrentRecipeId()
end

builtin.WithComponentParams = DeclareBuiltinLayoutChildWithUserdata("WithComponentParams", function (compParams)
	callingRecipeCtx:appendChildToResult(compParams.item)
end)

local function fixIsEnabledBool(isEnabledFn)
	if not isEnabledFn then
		return nil
	end
	return function()
		local result = isEnabledFn()
		if type(result) == "boolean" then
			return result and api.gui.inputAction.InputActionState.Enabled or api.gui.inputAction.InputActionState.Inactive
		end
		return result
	end
end

local function makeDropContext(fns)
	local getAllItems = function()
		return api.gui.dnd.getAllTransferData()
	end
	local getItems = fns.filter and function()
		local result = {}
		local all = api.gui.dnd.getAllTransferData()
		for __, v in ipairs(all) do
			if (fns.filter(v.type, v.data)) then
				result[#result + 1] = v
			end
		end
		return result
	end or getAllItems
	local dropContext = {
		getItems = getItems,
		getAllItems = getAllItems,
		anyMatch = function()
			return next(getItems()) ~= nil
		end
	}
	return dropContext
end
local function makeDnDListener(fns)
	return function(event)
		if event.type == api.gui.dnd.Event.Type.DragStarted then
			if fns.grab then
				local grabbed, cursor = fns.grab()
				if not grabbed then
					return false
				end
				for __, item in ipairs(grabbed) do
					api.gui.dnd.addTransferData(event, item, item)
				end
				if not cursor then
					cursor = 1010 -- "Grab" in gui_react_util.tl
				end
				if cursor then
					api.gui.dnd.setCursor(cursor)
				end
				return true
			end
		elseif event.type == api.gui.dnd.Event.Type.Drop then
			if fns.drop then
				return fns.drop(makeDropContext(fns)) or false
			end
		elseif event.type == api.gui.dnd.Event.Type.DragEntered then
			if fns.enter then
				return fns.enter(makeDropContext(fns)) or false
			end
		elseif event.type == api.gui.dnd.Event.Type.DragExited then
			if fns.exit then
				return fns.exit(makeDropContext(fns)) or false
			end
		end
		return false
	end
end

return {
	RegisterRecipe = RegisterRecipe,
	DeclareBuiltin = DeclareBuiltin,
	DeclareBuiltinWithUserdata = DeclareBuiltinWithUserdata,
	DeclareBuiltinLayoutChildWithUserdata = DeclareBuiltinLayoutChildWithUserdata,
	RegisterWrapperRecipe = RegisterWrapperRecipe,
	RegisterPluginRecipe = RegisterPluginRecipe,

	GetRecipeId = GetRecipeId,
	GetRecipeName = GetRecipeName,

	useState = useState,
	useStateLazy = useStateLazy,
	useMirrorState = useMirrorState,
	useDependentState = useDependentState,
	useRef = useRef,
	useRefLazy = useRefLazy,
	useMirrorRef = useMirrorRef,
	useDependentRef = useDependentRef,
	useNodeRef = function() return useRef(nil) end,
	useSelfRef = useSelfRef,
	findOldChild = findOldChild,
	findOldChildByLocalKey = findOldChildByLocalKey,

	onPausedChange = onPausedChange,
	useChildPausedModes = useChildPausedModes,
	onStep = onStep,
	onStepTimer = onStepTimer,
	onMount = onMount,
	onUnmount = onUnmount,
	onEvent = onEvent,
	onAnyEvent = onAnyEvent, -- debug only (too slow)
	provideApi = provideApi,
	useAction = useAction,
	onMouseEvent = function (fn) useComponentInternals().mouseListener = fn end,
	onDragAndDrop = function (fn) useComponentInternals().dragAndDropListener = makeDnDListener(fn) end,
	setName = function (name) useComponentInternals().name = name end, -- builtin use only, do NOT "expose" in d.tl (let alone use it in .tl)
	setStyleClasses = function (...) useComponentInternals().styleClasses = table.concat(table.pack(...), ",") end,
	setRestrictMouseFocus = function (restrictMouseFocus) useComponentInternals().restrictMouseFocus = restrictMouseFocus end,
	setForceFocusable = function (forceFocusable) useComponentInternals().forceFocusable = forceFocusable end,
	setDisableFocusable = function (disableFocusable) useComponentInternals().disableFocusable = disableFocusable end,
	setIndicateSelectionWithMouseHoverOnly = function(indicateSelectionWithMouseHoverOnly) useComponentInternals().indicateSelectionWithMouseHoverOnly = indicateSelectionWithMouseHoverOnly end,
	setMouseTransparent = function (transparent) useComponentInternals().mouseTransparent = transparent end,
	setLightweight = function (lightweight) useComponentInternals().lightweight = true end,
	setClipContent = function (clipContent) useComponentInternals().clipContent = true end,
	setPreferredFocusChild = function (childNodeRef) useComponentInternals().preferredFocusChild = childNodeRef end,
	useInputAction = function (ia, what)
		local internals = useComponentInternals()
		internals:setInputActionConfig(ia, what)
	end,

	style = style,
	ref = ref,
	iaHandler = function (handlerFn, isEnabledFn, buttonPromptTextOverride, acceptRepeatedPresses, isActive)
		local handlerCfg = api.gui.react.detail.IAHandle.new()
		handlerCfg.handlerFn = handlerFn
		handlerCfg.isEnabledFn = fixIsEnabledBool(isEnabledFn)
		if buttonPromptTextOverride then
			handlerCfg.promptTextOverride = buttonPromptTextOverride
		end
		handlerCfg.isActive = isActive
		if acceptRepeatedPresses then
			handlerCfg.mode = 1
		end
		return handlerCfg
	end,
	iaHandlerExtended = function (handlerFn, isEnabledFn, buttonPromptTextOverride, isActive)
		local handlerCfg = api.gui.react.detail.IAHandle.new()
		handlerCfg.handlerFn = handlerFn
		handlerCfg.isEnabledFn = fixIsEnabledBool(isEnabledFn)
		if promptTextOverride then
			handlerCfg.promptTextOverride = buttonPromptTextOverride
		end
		handlerCfg.isActive = isActive
		handlerCfg.mode = 2
		return handlerCfg
	end,
	iaFocusTraversal = function (horizontal, forward, allowBubbleUp)
		local handlerCfg = api.gui.react.detail.IAFocusTraversal.new()
		handlerCfg.horizontal = horizontal
		handlerCfg.forward = forward
		handlerCfg.allowBubbleUp = (allowBubbleUp == true)
		return handlerCfg
	end,
	iaForward = function (targetRef, targetAction)
		local forwardCfg = api.gui.react.detail.IAForward.new()
		forwardCfg.targetRef = targetRef
		forwardCfg.targetAction = targetAction
		return forwardCfg
	end,

	fireEvent = api.gui.react.fireEvent,

	getPlugins = getPlugins,

	RegisterExtensionPoint = RegisterExtensionPoint,
	RegisterExtensionPoint0 = RegisterExtensionPoint,
	RegisterWrapperExtensionPoint = RegisterWrapperExtensionPoint,
	RegisterWrapperExtensionPoint0 = RegisterWrapperExtensionPoint,
	RegisterTool = RegisterTool,

	GloballyReplaceRecipeBeforeInitInternal = GloballyReplaceRecipeBeforeInitInternal,
	CallOriginalRecipe = CallOriginalRecipe,

	getCallingRecipeCtx = function()
		return callingRecipeCtx
	end,

	getCurrentRecipeName = getCurrentRecipeName,
	getCurrentRecipeId = getCurrentRecipeId,
	enqueueDeferredStep = enqueueDeferredStep,
	enqueueJoin = enqueueJoin,
	enqueueParallel = enqueueParallel,

	builtin = builtin
}
